### ISSUE TITLE
System type is determined incorrectly

### ISSUE THREAD

**Issue by szhorvat** [QTechTheory/QuESTlink#118]
It appears that `CreateDownloadedQuESTEnv` uses `$OperatingSystem` to select a binary. This does not guarantee compatibility. It would be more appropriate to use `$SystemID` instead, which does. For example, `$OperatingSystem` will be `"Linux"` regardless of whether the software is running on x86 (32-bit), x86_64 or ARM (Mathematica is available for the Raspberry Pi).

**Comment by TysonRayJones** [comment]
Hi there,

Apologies for not seeing this issue until now (I strangely didn't get a notification)!
I'm not entirely sure what you mean. QuESTlink gets compiled using [Github CD](https://github.com/QTechTheory/QuESTlink/tree/master/.github/workflows), so has a limited choice of operating systems (3). It's not really feasible to over-engineer the CD to produce binaries for every possible chip, or `$SystemID`.
Users on incompatible platforms will have to compile themselves, as outlined [here](https://github.com/QTechTheory/QuESTlink/tree/master/Doc#compiling).

**Comment by szhorvat** [comment]
I am not requesting support for all platforms. I was simply pointing out that the way you select a binary to download is wrong, and will end up downloading an incompatible binary.

You should not use `$OperatingSystem` to select a binary because `$OperatingSystem` will have the same values on several different, incompatible systems. You should use `$SystemID` instead, as only `$SystemID` is sufficiently specific to choose a compatible binary. 

In fact, Mathematica has mechanisms to use `$SystemID` for automatically selecting an appropriate installable MathLink program. See the 3rd point under Details here: https://reference.wolfram.com/language/ref/Install.html You could consider using the directory structure there instead of putting all executables in the same directory and having different names for different OSs. This is a more extensible, more maintainable solution.

Of course it's up to you. This was meant as a helpful suggestion.

**Comment by szhorvat** [comment]
I am referring to line 524 here: https://raw.githubusercontent.com/QTechTheory/QuESTlink/master/Link/QuESTlink.m and everything that follows from there.

**Comment by TysonRayJones** [comment]
Hi,

I think I have to disagree with you on this. We can only produce _three_ binaries due to the limitations of Github CD, and `$OperatingSystem` is the best way to distinguish them. We cannot interpret and cater for every value of `$SystemID`. If an executable is incompatible despite the best guess of `$OperatingSystem`, then we have no other binaries to offer it - downloading an incompatible binary, given none compatible are available, doesn't seem the end of the world.

Given we maintain merely 3 executables, for a software that we encourage users to compile themselves for e.g. hardware-acceleration, a folder of `Binaries` seems fine to me. 

If I've misunderstood you, or you have a better idea for increasing QuESTlink's portability, please let me know!

**Comment by szhorvat** [comment]
> "despite the best guess of `$OperatingSystem`"

My point is: you don't have to guess. This is not a "best" guess. You have all the information to decide compatibility (`$SystemID`) and issue a proper error message instead of letting things fail arbitrarily.

Of course I respect your choice not to do this check, and let users deal with the failure. I simply tried to bring a very easy improvement to your attention because I care about the health of Mathematica's package ecosystem. A big reason why so many Mathematica users distrust packages (or anything that is not built-in) is that so many packages come with their own custom---and often unreliable or misbehaving---installer.  Of course, this is in big part due to Wolfram Research's lackluster support for package developers. For example, the paclet format (which should really be the only way any modern Mathematica package is distributed) only got officially documented very recently.
