### ISSUE TITLE
[minor] two-qubit Kraus map error message talks of "single-qubit Kraus" 

### ISSUE THREAD

**Issue by lm1909** [QTechTheory/QuESTlink#124]
The error message which occurs when too many operators are passed to a _two-qubit_ Kraus map says "xx operators were passed to _single-qubit_ Kraus[ops]", which is potentially confusing.

**To reproduce:** ApplyCircuit on a circuit that contains a two-bit Kraus_i,j[] which has at least 17 operators in its argument.

**Cause:** error message is not differentiated according to `numTargs` in [Link/quest_link.cpp:1262](https://github.com/QTechTheory/QuESTlink/blob/abd21424971fda98e5145bface69bf426d75bf91/Link/quest_link.cpp#L1262-L1267).

**Comment by TysonRayJones** [comment]
Well spotted! I've patched this in a working branch (8f779812afccb62caef87aa00cec503c2576a610) since it's close to a release.

It will now correctly read:

> ![image](https://user-images.githubusercontent.com/29574749/107969567-d7762d80-6fa7-11eb-8f09-cb5b15521c4d.png)

Thanks very much!
